# Generated by Django 5.2.4 on 2025-08-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='total_calories_burned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
