# Generated by Django 5.2.4 on 2025-08-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_analytics_total_calories_burned'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='workout_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
