# Generated by Django 5.2.4 on 2025-08-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_analytics_workout_duration_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='workout_duration_minutes',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
