# Generated by Django 5.2.4 on 2025-08-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_analytics_workout_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='workout_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
