# Generated by Django 5.2.4 on 2025-09-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_analytics_workout_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='met_value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
