# Generated by Django 5.2.4 on 2025-09-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_analytics_met_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='met_value',
        ),
        migrations.AddField(
            model_name='category',
            name='met_value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
