# Generated by Django 5.2.4 on 2025-09-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_remove_analytics_met_value_category_met_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='met_value',
        ),
    ]
