# Generated by Django 5.2.4 on 2025-09-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_remove_category_met_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytics',
            old_name='workout_duration_minutes',
            new_name='weekly_workout_duration_minutes',
        ),
        migrations.AddField(
            model_name='analytics',
            name='average_intensity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='analytics',
            name='estimated_1rm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
