# Generated by Django 5.2.4 on 2025-09-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_rename_workout_duration_minutes_analytics_weekly_workout_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='estimated_1rm',
        ),
    ]
