# Generated by Django 5.2.4 on 2025-09-05 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_remove_analytics_estimated_1rm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='week_start_date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='analytics',
            constraint=models.UniqueConstraint(fields=('user', 'week_start_date'), name='unique_analytics_per_user_per_week'),
        ),
    ]
